services:
  - type: web
    name: whisper-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
